services:
  xstorage.contentreadapi:
    image: xstorage.contentreadapi
    env_file:
      - infra/XStorage.ContentReadApi/.env
    build:
      context: .
      dockerfile: infra/XStorage.ContentReadApi/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - /Volumes/AnnaR:/Volumes/AnnaR
      - /Volumes/AnnaB:/Volumes/AnnaB