services:
  xstorage.contentreadapi:
    image: xstorage.contentreadapi
    env_file:
      - infra/XStorage.ContentReadApi/.env
    build:
      context: .
      dockerfile: infra/XStorage.ContentReadApi/Dockerfile
