using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;

namespace XStorage.EnvKeysGenerator;

[Generator(LanguageNames.CSharp)]
public sealed class EnvVarsGenerator : IIncrementalGenerator
{
    private const string CsvFileName = "EnvVars.csv";
    private const string OutputNamespace = "XStorage.Common"; // change if you want

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var csvFiles = context.AdditionalTextsProvider
            .Where(static f => f.Path.EndsWith(CsvFileName, StringComparison.OrdinalIgnoreCase))
            .Select((file, ct) => (path: file.Path, text: file.GetText(ct)?.ToString()));

        context.RegisterSourceOutput(csvFiles.Collect(), static (spc, files) =>
        {
            if (files.IsDefaultOrEmpty)
                return;

            var allRows = new List<Row>();

            foreach (var (path, text) in files)
            {
                if (string.IsNullOrWhiteSpace(text))
                    continue;

                var parsed = ParseCsv(text!, path);
                allRows.AddRange(parsed.Rows);
                foreach (var d in parsed.Diagnostics) spc.ReportDiagnostic(d);
            }

            if (allRows.Count == 0)
                return;

            foreach (var d in Validate(allRows)) spc.ReportDiagnostic(d);

            var source = Emit(allRows);
            spc.AddSource("XStorage.EnvVars.g.cs", SourceText.From(source, Encoding.UTF8));
        });
    }

    private static string Emit(List<Row> rows)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine();
        sb.AppendLine($"namespace {OutputNamespace};");
        sb.AppendLine();

        // EnvVarId (key identifiers)
        sb.AppendLine("public enum EnvVarId");
        sb.AppendLine("{");
        foreach (var r in rows.OrderBy(r => r.Name, StringComparer.Ordinal))
            sb.Append("    ").Append(r.Name).AppendLine(",");
        sb.AppendLine("}");
        sb.AppendLine();

        // EnvVar<T>
        sb.AppendLine("public readonly struct EnvVar<T>");
        sb.AppendLine("{");
        sb.AppendLine("    public string Key { get; }");
        sb.AppendLine("    private readonly Func<T, string> _format;");
        sb.AppendLine();
        sb.AppendLine("    public EnvVar(string key, Func<T, string> format)");
        sb.AppendLine("    {");
        sb.AppendLine("        Key = key;");
        sb.AppendLine("        _format = format;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    public string Format(T value) => _format(value);");
        sb.AppendLine("}");
        sb.AppendLine();

        // Generate enums for allowed values
        var constrained = rows
            .Where(r => r.AllowedValues is { Count: > 0 })
            .OrderBy(r => r.Name, StringComparer.Ordinal)
            .ToList();

        foreach (var r in constrained)
        {
            var enumName = $"{r.Name}Value";
            sb.AppendLine($"public enum {enumName}");
            sb.AppendLine("{");
            foreach (var av in r.AllowedValues!)
                sb.Append("    ").Append(av.EnumMember).AppendLine(",");
            sb.AppendLine("}");
            sb.AppendLine();
        }

        // EnvVars
        sb.AppendLine("public static class EnvVars");
        sb.AppendLine("{");

        foreach (var r in rows.OrderBy(r => r.Name, StringComparer.Ordinal))
        {
            if (!string.IsNullOrWhiteSpace(r.Description))
            {
                sb.AppendLine("    /// <summary>");
                sb.Append("    /// ").Append(EscapeXml(r.Description!)).AppendLine();
                sb.AppendLine("    /// </summary>");
            }

            if (r.AllowedValues is { Count: > 0 })
            {
                var enumName = $"{r.Name}Value";

                sb.Append("    public static readonly EnvVar<").Append(enumName).Append("> ").Append(r.Name).AppendLine(" =");
                sb.Append("        new(@\"").Append(r.Key.Replace("\"", "\"\"")).Append("\", v => ").AppendLine(EmitFormatterExpr(r, enumName) + ");");
            }
            else
            {
                sb.Append("    public static readonly EnvVar<string> ").Append(r.Name).AppendLine(" =");
                sb.Append("        new(@\"").Append(r.Key.Replace("\"", "\"\"")).AppendLine("\", v => v);");
            }

            sb.AppendLine();
        }

        // KeysById map
        sb.AppendLine("    public static readonly IReadOnlyDictionary<EnvVarId, string> KeysById =");
        sb.AppendLine("        new Dictionary<EnvVarId, string>");
        sb.AppendLine("        {");
        foreach (var r in rows.OrderBy(r => r.Name, StringComparer.Ordinal))
            sb.Append("            [EnvVarId.").Append(r.Name).Append("] = ").Append(r.Name).AppendLine(".Key,");
        sb.AppendLine("        };");

        sb.AppendLine("}");
        sb.AppendLine();

        return sb.ToString();
    }

    private static string EmitFormatterExpr(Row r, string enumName)
    {
        // Special-case boolean allowed values: format to lowercase "true"/"false"
        if (IsBoolAllowedValues(r.AllowedValues!))
            return $"v == {enumName}.True ? \"true\" : \"false\"";

        // Otherwise, map each enum member back to the original literal string
        var sb = new StringBuilder();
        sb.AppendLine("v switch");
        sb.AppendLine("        {");
        foreach (var av in r.AllowedValues!)
        {
            sb.Append("            ").Append(enumName).Append(".").Append(av.EnumMember)
              .Append(" => ").Append("@\"").Append(av.Raw.Replace("\"", "\"\"")).AppendLine("\",");
        }
        sb.AppendLine("            _ => throw new ArgumentOutOfRangeException(nameof(v))");
        sb.Append("        }");
        return sb.ToString();
    }

    private static bool IsBoolAllowedValues(List<AllowedValue> allowed)
    {
        if (allowed.Count != 2) return false;
        var hasTrue = allowed.Any(v => v.Raw.Equals("true", StringComparison.OrdinalIgnoreCase));
        var hasFalse = allowed.Any(v => v.Raw.Equals("false", StringComparison.OrdinalIgnoreCase));
        return hasTrue && hasFalse;
    }

    private static string EscapeXml(string s)
        => s.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;");

    private static ImmutableArray<Diagnostic> Validate(List<Row> rows)
    {
        var diags = ImmutableArray.CreateBuilder<Diagnostic>();

        foreach (var g in rows.GroupBy(r => r.Name, StringComparer.Ordinal))
            if (g.Count() > 1)
                diags.Add(Diagnostic.Create(DuplicateName, Location.None, g.Key));

        foreach (var g in rows.GroupBy(r => r.Key, StringComparer.Ordinal))
            if (g.Count() > 1)
                diags.Add(Diagnostic.Create(DuplicateKey, Location.None, g.Key));

        return diags.ToImmutable();
    }

    private static (List<Row> Rows, ImmutableArray<Diagnostic> Diagnostics) ParseCsv(string csv, string path)
    {
        var rows = new List<Row>();
        var diags = ImmutableArray.CreateBuilder<Diagnostic>();

        var lines = csv
            .Split(new[] { "\r\n", "\n" }, StringSplitOptions.None)
            .Select(l => l.Trim())
            .Where(l => !string.IsNullOrWhiteSpace(l))
            .Where(l => !l.StartsWith("#", StringComparison.Ordinal))
            .ToList();

        if (lines.Count == 0)
            return (rows, diags.ToImmutable());

        var header = SplitCsvLine(lines[0]);
        var nameIdx = IndexOf(header, "Name");
        var keyIdx = IndexOf(header, "Key");
        var descIdx = IndexOf(header, "Description");      // optional
        var allowedIdx = IndexOf(header, "AllowedValues"); // optional

        if (nameIdx < 0 || keyIdx < 0)
        {
            diags.Add(Diagnostic.Create(BadHeader, Location.None, path));
            return (rows, diags.ToImmutable());
        }

        for (int i = 1; i < lines.Count; i++)
        {
            var cols = SplitCsvLine(lines[i]);

            if (nameIdx >= cols.Count || keyIdx >= cols.Count)
            {
                diags.Add(Diagnostic.Create(BadRow, Location.None, path, i + 1));
                continue;
            }

            var nameRaw = cols[nameIdx].Trim();
            var keyRaw = cols[keyIdx].Trim();
            var descRaw = (descIdx >= 0 && descIdx < cols.Count) ? cols[descIdx].Trim() : null;
            var allowedRaw = (allowedIdx >= 0 && allowedIdx < cols.Count) ? cols[allowedIdx].Trim() : null;

            if (string.IsNullOrWhiteSpace(nameRaw) || string.IsNullOrWhiteSpace(keyRaw))
            {
                diags.Add(Diagnostic.Create(BadRow, Location.None, path, i + 1));
                continue;
            }

            var name = ToPascalIdentifier(nameRaw);
            if (!SyntaxFacts.IsValidIdentifier(name))
            {
                diags.Add(Diagnostic.Create(BadIdentifier, Location.None, nameRaw, path, i + 1));
                continue;
            }

            List<AllowedValue>? allowed = null;
            if (!string.IsNullOrWhiteSpace(allowedRaw))
                allowed = ParseAllowedValues(allowedRaw!, path, i + 1, diags);

            rows.Add(new Row(
                Name: name,
                Key: keyRaw,
                Description: string.IsNullOrWhiteSpace(descRaw) ? null : descRaw,
                AllowedValues: allowed));
        }

        return (rows, diags.ToImmutable());

        static int IndexOf(List<string> headerCols, string name)
            => headerCols.FindIndex(c => c.Equals(name, StringComparison.OrdinalIgnoreCase));
    }

    private static List<AllowedValue> ParseAllowedValues(
        string allowedRaw,
        string path,
        int lineNo,
        ImmutableArray<Diagnostic>.Builder diags)
    {
        // Pipe-separated (recommended): "A|B|C" (also accepts ';')
        var parts = allowedRaw
            .Split(new[] { '|', ';' }, StringSplitOptions.RemoveEmptyEntries)
            .Select(p => p.Trim())
            .Where(p => p.Length > 0)
            .ToList();

        var list = new List<AllowedValue>();
        var seen = new HashSet<string>(StringComparer.OrdinalIgnoreCase);

        foreach (var raw in parts)
        {
            var member = ToEnumMember(raw);

            if (!SyntaxFacts.IsValidIdentifier(member))
            {
                diags.Add(Diagnostic.Create(BadAllowedValue, Location.None, raw, path, lineNo));
                continue;
            }

            if (!seen.Add(member))
            {
                diags.Add(Diagnostic.Create(DuplicateAllowedValue, Location.None, raw, path, lineNo));
                continue;
            }

            list.Add(new AllowedValue(Raw: raw, EnumMember: member));
        }

        return list;
    }

    private static string ToEnumMember(string raw)
    {
        // normalize booleans
        if (raw.Equals("true", StringComparison.OrdinalIgnoreCase)) return "True";
        if (raw.Equals("false", StringComparison.OrdinalIgnoreCase)) return "False";

        // pure integer => prefix underscore (5672 => _5672)
        if (raw.All(char.IsDigit))
            return "_" + raw;

        // "system-test" / "system test" / "SystemTest" => "SystemTest"
        var pascal = ToPascalIdentifier(raw);

        // if starts with digit after pascalization, prefix underscore
        if (pascal.Length > 0 && char.IsDigit(pascal[0]))
            pascal = "_" + pascal;

        return pascal.Length == 0 ? "Value" : pascal;
    }

    private static List<string> SplitCsvLine(string line)
    {
        // Minimal CSV: commas + quotes ("") supported
        var result = new List<string>();
        var sb = new StringBuilder();
        bool inQuotes = false;

        for (int i = 0; i < line.Length; i++)
        {
            var c = line[i];

            if (c == '"')
            {
                if (inQuotes && i + 1 < line.Length && line[i + 1] == '"')
                {
                    sb.Append('"');
                    i++;
                }
                else
                {
                    inQuotes = !inQuotes;
                }
                continue;
            }

            if (c == ',' && !inQuotes)
            {
                result.Add(sb.ToString());
                sb.Clear();
                continue;
            }

            sb.Append(c);
        }

        result.Add(sb.ToString());
        return result;
    }

    private static string ToPascalIdentifier(string s)
    {
        var parts = s
            .Replace("-", " ")
            .Replace("_", " ")
            .Split(new[] { ' ' }, StringSplitOptions.RemoveEmptyEntries);

        var sb = new StringBuilder();
        foreach (var p in parts)
        {
            var t = p.Trim();
            if (t.Length == 0) continue;

            sb.Append(char.ToUpperInvariant(t[0]));
            if (t.Length > 1) sb.Append(t.Substring(1));
        }

        return sb.Length == 0 ? "Unnamed" : sb.ToString();
    }

    private sealed record AllowedValue(string Raw, string EnumMember);

    private sealed record Row(
        string Name,
        string Key,
        string? Description,
        List<AllowedValue>? AllowedValues);

    // Diagnostics
    private static readonly DiagnosticDescriptor BadHeader = new(
        id: "XSG001",
        title: "EnvVars CSV has invalid header",
        messageFormat: "CSV '{0}' must have headers: Name,Key,(optional)Description,(optional)AllowedValues",
        category: "XStorage.Generators",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor BadRow = new(
        id: "XSG002",
        title: "EnvVars CSV row is invalid",
        messageFormat: "CSV '{0}' has invalid row at line {1}",
        category: "XStorage.Generators",
        DiagnosticSeverity.Warning,
        isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor BadIdentifier = new(
        id: "XSG003",
        title: "EnvVars CSV Name cannot be converted to a valid identifier",
        messageFormat: "Name '{0}' is not a valid identifier (CSV '{1}', line {2})",
        category: "XStorage.Generators",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor DuplicateName = new(
        id: "XSG004",
        title: "Duplicate Name in EnvVars CSV",
        messageFormat: "Duplicate Name '{0}' found in EnvVars CSV",
        category: "XStorage.Generators",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor DuplicateKey = new(
        id: "XSG005",
        title: "Duplicate Key in EnvVars CSV",
        messageFormat: "Duplicate Key '{0}' found in EnvVars CSV",
        category: "XStorage.Generators",
        DiagnosticSeverity.Warning,
        isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor BadAllowedValue = new(
        id: "XSG006",
        title: "EnvVars CSV AllowedValues contains an invalid value",
        messageFormat: "Allowed value '{0}' cannot be converted to a valid enum member (CSV '{1}', line {2})",
        category: "XStorage.Generators",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor DuplicateAllowedValue = new(
        id: "XSG007",
        title: "EnvVars CSV AllowedValues contains duplicates",
        messageFormat: "Duplicate allowed value '{0}' (after normalization) in CSV '{1}', line {2}",
        category: "XStorage.Generators",
        DiagnosticSeverity.Warning,
        isEnabledByDefault: true);
}
